stages:
  - build

variables:
  BAZEL_VERSION: "7.1.1"

build:
  stage: build
  image: debian:12-slim
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - /usr/local/bin/bazel
      - .bazel_cache/
  script:
    - apt-get update && apt-get install -y wget clang clang-format libboost-all-dev git
    - if [ ! -f /usr/local/bin/bazel ]; then wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-linux-x86_64 -O /usr/local/bin/bazel; fi
    - chmod +x /usr/local/bin/bazel
    - echo "Bazel setup done."
    - clang-format -i src/*/*.h src/*/*.cc unit_tests/*/*.cc unit_tests/utils.h
    - git diff --exit-code
    - bazel build //src/...
    - bazel test //unit_tests/...
