stages:
  - build

build:
  stage: build
  image:
    name: debian:12-slim
    entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - apt-get update && apt-get install -y wget clang clang-format-14 libboost-all-dev git
    - wget https://github.com/bazelbuild/bazel/releases/download/7.1.1/bazel-7.1.1-linux-x86_64 -O /usr/local/bin/bazel
    - chmod +x /usr/local/bin/bazel
    - bazel --version
    - bazel build //src/...
    - bazel test //unit_tests/...
    - clang-format-14 -i src/*/*.h src/*/*.cc
    - clang-format-14 -i unit_tests/*/*.cc unit_tests/*/*.h
    - set +e
    - FAILED_FORMAT=$(git status --porcelain | grep -F "M")
    - set -e
    - if [[ "${FAILED_FORMAT}" != "" ]] ; then echo "Formatting not conform"; exit 1; fi
