stages:
  - build

variables:
  BAZEL_VERSION: "7.1.1"

build:
  stage: build
  image: debian:12-slim
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - /usr/local/bin/bazel
  script:
    # Update and install necessary tools
    - apt-get update && apt-get install -y wget lsb-release software-properties-common gnupg2
    # Add LLVM repository
    - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
    - echo "deb http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-18 main" | tee /etc/apt/sources.list.d/llvm.list
    - echo "deb-src http://apt.llvm.org/bookworm/ llvm-toolchain-bookworm-18 main" | tee -a /etc/apt/sources.list.d/llvm.list
    - apt-get update
    # Install Clang 18 and Clang-Format 18
    - apt-get install -y clang clang-format-18 libboost-all-dev git
    - if [ ! -f /usr/local/bin/bazel ]; then wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-linux-x86_64 -O /usr/local/bin/bazel; fi
    - chmod +x /usr/local/bin/bazel
    - echo "Bazel setup done."
    - clang-format-18 --version
    - clang-format-18 -i src/*/*.h src/*/*.cc unit_tests/*/*.cc unit_tests/utils.h
    - git diff --exit-code
    - bazel build //src/...
    - bazel test //unit_tests/...
